// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCSBKdmMUxUaE7WYQ8z40a5YketKj87zQ',
    appId: '1:642970217514:android:da53a7417399aab119a753',
    messagingSenderId: '642970217514',
    projectId: 'shades-of-skin',
    storageBucket: 'shades-of-skin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTRF995zyK_qWPSSgAWchcoUvEqzY2qU',
    appId: '1:642970217514:ios:428c803ece76d0b719a753',
    messagingSenderId: '642970217514',
    projectId: 'shades-of-skin',
    storageBucket: 'shades-of-skin.firebasestorage.app',
    androidClientId: '642970217514-ncs3o3bhqacmebcg5612u1o8d49r2plj.apps.googleusercontent.com',
    iosClientId: '642970217514-55ajbtp8tmjkaeics9e8dveb0h3d3543.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
